### PR TITLE
Vendoring and build tool

### PR DESCRIPTION
**Pull request by nlamirault**
Using [govendor](https://github.com/kardianos/govendor), you could build this project : 

```
$ make build .
$ ./jam --help
Jam - 0.2.0
  -version
        print version and exit
$ ./jam -version
0.2.0
$ ./jam
Email: xxxxxxxx@gmail.com
Password: ***************
```

I also make some fix on types, without it i've got theses errors : 

```
$ go build .
# github.com/budkin/jam
./lib.go:46: cannot use t.DiscNumber (type float64) as type uint8 in field value
./lib.go:46: cannot use t.TrackNumber (type float64) as type uint8 in field value
./lib.go:47: cannot use t.PlayCount (type float64) as type uint32 in field value
./lib.go:47: cannot use t.Year (type float64) as type int in field value
```

### CODE REVIEW

**Comment by budkin** [comment]
Sorry, I forgot to push the changes I made in my fork of mjibson/gmusic. I've just done that, so it should compile alright, so no need in your "Fix types" commit, can you please cancel it? or tell me how I can do it? I'm not much familiar with team work on github, yours is my first pull request ever:D I'll look into other commits more closely in a bit

**Comment by nlamirault** [comment]
Done for updated gmusic and remove fix on types.

**Comment by budkin** [comment]
Something's wrong with your makefile, when I type "make build" it throws an error

```
`main.go:11:2: cannot find package "github.com/budkin/jam/version" in any of:
	/home/budkin/go/src/github.com/nlamirault/jam/vendor/github.com/budkin/jam/version (vendor tree)
	/usr/lib/go/src/github.com/budkin/jam/version (from $GOROOT)
	/home/budkin/go/src/github.com/budkin/jam/version (from $GOPATH)
make: *** [Makefile:61: build] Error 1
```

**Comment by nlamirault** [comment]
Strange ...

Why this path ? :
```
/home/budkin/go/src/github.com/nlamirault
```

**Comment by budkin** [comment]
Ah, sorry, my bad, I just cloned your repo and make'd install from there

**Pull request merged**
