### PR TITLE
vim like gg and G keybindings

### PR DESCRIPTION
**Pull request by avilanicolas**
I recently discover this repo and I've been liking it a lot so far, but the lack of vim-like `gg` and `G` keybindings bothered me. I decided to see how I could add those to the repo and these seem to work fairly well. My keyboard doesn't actually have an End or a Home key, so these are useful to me.

**Testing Done**
```make build```

I tried a few interesting combinations outside of the normal `gg` and `G` and no awkward behavior stood out to me. However, this does cause jam to crash when I use it on a playlist of 500+ songs. However, after using using `xmodmap` to simulate an End key input, that caused jam to fail as well, so my change hasn't introduced that bug.

A better solution to this would be to allow for more customizable keybindings, which I am considering doing.

### CODE REVIEW

**Comment by budkin** [comment]
why overcomplicate things? `g` is bound to no action at the moment, you can bind it to `home`

**Comment by avilanicolas** [comment]
How do you mean bind g to home, exactly? Do you mean to stop tracking `gg` and just have `g` map to scrollUp()? I only really chose `gg` because that's how it is in Vim, but making it just `g` is reasonable.

**Comment by budkin** [comment]
yeah, just do this
```
			case 'G':
 				app.scrollDown()
 			case 'g':
 				app.scrollUp()`
```

**Comment by avilanicolas** [comment]
Ah yes, of course, that simplifies things.

I've added the new commit, still builds, still works.

**Comment by budkin** [comment]
Thanks:)

**Pull request merged**
