### PR TITLE
[WIP] Refactoring using packages

### PR DESCRIPTION
**Pull request by nlamirault**
I'm trying to make a refactoring into packages : 

* auth: for Google Music authentication
* music: manage music library
* storage : database backend (BoltDB)
* ui: the terminal UI

I've got actually an error when i launch the UI : 

```
panic: runtime error: index out of range
goroutine 1 [running]:
                  panic(0x6c2200, 0xc42000c140)
                                                /home/nlamirault/Apps/go/src/runtime/panic.go:500 +0x1a1
                                                                                                        github.com/budkin/jam/ui.(*App).numAlb(0xc4209ec080, 0xfffffffffffffffe, 0xc4204979a6)
                /home/nlamirault/Apps/golang/src/github.com/budkin/jam/ui/events.go:30 +0x191
                                                                                             github.com/budkin/jam/ui.(*App).populateSongs.func1(0xc4203360e0, 0x7438a8, 0xc4203360e0)
        /home/nlamirault/Apps/golang/src/github.com/budkin/jam/ui/app.go:179 +0x15a
                                                                                   github.com/budkin/jam/vendor/github.com/boltdb/bolt.(*DB).View(0xc420116000, 0xc420497b68, 0x0, 0x0)
        /home/nlamirault/Apps/golang/src/github.com/budkin/jam/vendor/github.com/boltdb/bolt/db.go:629 +0xb5
                                                                                                            github.com/budkin/jam/ui.(*App).populateSongs(0xc4209ec080)
                                                                                                                                                                        /home/nlamirault/Apps/golang/src/github.com/budkin/jam/ui/app.go:193 +0x57
                                                                 github.com/budkin/jam/ui.(*App).printSongs(0xc4209ec080, 0x0, 0x29)
                                                                                                                                        /home/nlamirault/Apps/golang/src/github.com/budkin/jam/ui/tui.go:141 +0x43
                                 github.com/budkin/jam/ui.(*App).updateUI(0xc4209ec080)
                                                                                        /home/nlamirault/Apps/golang/src/github.com/budkin/jam/ui/tui.go:47 +0x217
                                                                                                                                                                  github.com/budkin/jam/ui.(*App).mainLoop(0xc4209ec080)
                                        /home/nlamirault/Apps/golang/src/github.com/budkin/jam/ui/app.go:333 +0xc8
                                                                                                                  github.com/budkin/jam/ui.(*App).Run(0xc4209ec080)
                                                                                                                                                                        /home/nlamirault/Apps/golang/src/github.com/budkin/jam/ui/app.go:143 +0x93
                                                                 main.doUI(0xc4200bd020, 0xc420116000, 0xc420116000, 0x0)
                                                                                                                                /home/nlamirault/Apps/golang/src/github.com/budkin/jam/main.go:90 +0x52
                      main.main()
                                        /home/nlamirault/Apps/golang/src/github.com/budkin/jam/main.go:78 +0xbc

```

### CODE REVIEW

**Comment by nlamirault** [comment]
If you have any idea ....

**Comment by budkin** [comment]
How do I git clone this and take a look?

**Comment by nlamirault** [comment]
You could clone my repository into $GOPATH/src/github.com/budkin/jam

**Comment by budkin** [comment]
ah, branches, right!

**Comment by nlamirault** [comment]
To another branch also

**Comment by budkin** [comment]
curPos is the cursor position relatively to the top of the window, take a look at `ui/app.go:123` && `124`, right now the values are set to -1 and 0, but should be 1 and 2

**Comment by budkin** [comment]
otherwise you've done a great job

**Comment by nlamirault** [comment]
Thanks. I've got another problem : 
I can't make that : 
```
app.Songs = app.Songs[app.Albums[app.Artists[app.Status.CurPos[false]-1+app.Status.ScrOffset[false]]][app.Status.NumAlbum[true]]]
```
to replace that : https://github.com/budkin/jam/blob/master/ui.go
```
songs := songs[albums[artists[curPos[false]-1+scrOffset[false]]][numAlbum[true]]]
```

**Comment by budkin** [comment]
I just deleted that line and everything seems to be working fine

**Comment by budkin** [comment]
ah. my mistake, it is used, you can replace it with whatever name you like 
```
songs := app.Songs[app.Albums[app.Artists[app.Status.CurPos[false]-1+app.Status.ScrOffset[false]]][app.Status.NumAlbum[true]]]

app.Status.NumTrack = len(songs) - 1

```

**Comment by nlamirault** [comment]
Great :) i make a mistake between current songs and application songs.
I've got another problem with screen. It seems all songs are displayed. Strange.

**Comment by budkin** [comment]
because you should reinitialize app.Songs on each up and down stroke

**Comment by budkin** [comment]
Also, I don't like the new look, I'm pretty sure it won't look good on windows, because you use colors. And move linux.go to /music/ . What is it doing in UI?

**Comment by budkin** [comment]
it doesn't look good even on my linux machine
2017-01-28-211815_960x1080_img

**Comment by nlamirault** [comment]
Sure :-1:

**Comment by budkin** [comment]
https://github.com/budkin/jam/pull/12#issuecomment-275864074
I mean this line
https://github.com/budkin/jam/blob/master/ui.go#L705

**Comment by budkin** [comment]
Nice. But why does it start so slowly? It takes a few seconds. The version in master starts instantly

**Comment by budkin** [comment]
seems like it syncs the database each time it starts

**Comment by nlamirault** [comment]
:-1: .
I will try to fix that.

**Comment by nlamirault** [comment]
It seems better now. But i've got a freeze when i try to read a music file.

**Comment by nlamirault** [comment]
Great. It works fine now :+1:

**Comment by budkin** [comment]
Take a look at my changes, it doesn't build at the moment

**Comment by nlamirault** [comment]
OK. I make some changes. It build. I could push if you like.

**Comment by budkin** [comment]
sure

**Comment by budkin** [comment]
I'll test it for a bit, and then merge (if I figure out how)

**Comment by nlamirault** [comment]
:+1:

**Comment by budkin** [comment]
I fucked up the readme, and possibly something else

**Comment by nlamirault** [comment]
:+1:

**Pull request merged**
