### PR TITLE
support Windows

### PR DESCRIPTION
**Pull request by koron**
This PR makes jam works on Windows.

You should get a dependency before building on Windows, with this command:

    go get -v -u github.com/koron/go-waveout

### CODE REVIEW

**Comment by budkin** [comment]
It crashes with the message "failed to create waveout: device ID out of range" 

I'm using windows XP x64 in a virtual machine

**Comment by budkin** [comment]
although, I'm building on linux

**Comment by budkin** [comment]
I apologize, that's probably because my virtual machine is not configured to work with sound properly

**Comment by koron** [comment]
thx!

**Pull request merged**
